[package]
name = "dull"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "*", features = ["derive"] }
codespan = "*"
codespan-reporting = "*"
smallvec = "*"

[dev-dependencies]
walkdir = "2"